### ISSUE TITLE
Breaking changes in Ghost 0.10.0

### ISSUE THREAD

**Issue by kirrg001** [thombuchi/ghost-google-cloud-storage#1]
Hey!

We released Ghost 0.10.0.
It contains breaking changes for the storage adapter, see https://github.com/TryGhost/Ghost/wiki/Using-a-custom-storage-module.

**Comment by prenaudin** [comment]
Pull Request here https://github.com/thombuchi/ghost-google-cloud-storage/pull/2

**Comment by thombuchi** [comment]
Thanks prenaudin, i was going to add the support this weekend. I will add you in the readme later ;)

**Comment by prenaudin** [comment]
Thanks for adding me as a contributor.
Did you publish a new release on npm?
